---
author: "Daniel Anderson"
date: "04/07/2022"
params:
  file: "data/AISD-West.csv"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
---

---
title: "Individual School Report: `r gsub("SAISD-",  "", gsub("\\.csv", "", basename(params$file))) `"
---

\newpage

```{r include = FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(knitr.kable.NA = '0%')

theme_set(
  theme_minimal(15)
)

d <- readr::read_csv(params$file)
new_names <- c(
  "adults_model_kindness",
  "kindness_regular_classroom",
  "kindness_regular_school",
  "teacher_kind",
  "encouraged_kind",
  "grade"
)
names(d)[8:13] <- new_names

```

# All Grades

```{r }
nms <- c(
  "Response", 
  "1. The adults in my school model kindness.",
  "2. Kindness happens regularly in my classrooms.",
  "3. Kindness happens regularly in my school.",
  "4. My teacher is kind.",
  "5. At my school I am encouraged to be kind."
)
create_percent <- function(x) {
  paste0(format(round(x, 2), nsmall = 2), "%")  
}

create_table <- function(data) {
 cross_tabs <- data %>% 
  select(respondent_id, contains("kind")) %>% 
  pivot_longer(-respondent_id) %>% 
  drop_na() %>% 
  count(name, value) %>% 
  group_by(name) %>% 
  mutate(
    percent = (n / sum(n)) * 100,
    percent = create_percent(percent)
  ) %>% 
  select(-n) %>% 
  pivot_wider(names_from = "name", values_from = "percent") %>% 
  mutate(
    value = factor(
      value, 
      levels = c(
        "Disagree a lot",
        "Disagree a little",
        "Don't agree or disagree",
        "Agree a little",
        "Agree a lot"
      )
    )
  )
 
  names(cross_tabs) <- nms
  cross_tabs
}

create_table(d) %>% 
  knitr::kable(digits = 2)
```

```{r }
get_counts <- function(data, variable) {
  data %>% 
    select({{variable}}) %>% 
    drop_na() %>% 
    count({{variable}}) %>% 
    mutate(
      prop = n / sum(n),
      labels = create_percent(prop * 100),
      nudge_amount = ifelse(prop > 0.1, -0.09, 0.01),
      label_color = ifelse(prop > 0.1, "white", "black"),
      {{variable}} := factor(
        {{variable}},
        levels = c(
          "Disagree a lot",
          "Disagree a little",
          "Don't agree or disagree",
          "Agree a little",
          "Agree a lot"
        )
      )
    )
}

plot_counts <- function(counts_df, item_num, grade) {
  nm <- names(counts_df)[1]
  grade_label <- ifelse(
    is.null(grade), 
    "All Grades", 
    paste0("Grade ", grade)
  )
  
  ggplot(counts_df, aes(prop, !!sym(nm))) +
  geom_col(fill = "cornflowerblue", 
           color = colorspace::darken("cornflowerblue", .3),
           alpha = 0.9) +
  scale_x_continuous(
    "Percentage", 
    labels = scales::percent,
    expand = c(0, 0)
  ) +
  scale_y_discrete(drop = FALSE) +
  geom_text(
    aes(label = labels, color = label_color), 
    nudge_x = counts_df$nudge_amount,
    hjust = 0
  ) +
  labs(
    title = nms[item_num + 1],
    y = "",
    caption = paste0(grade_label, "; n = ", sum(counts_df$n))
  ) +
  scale_color_identity() +
  guides(color = "none") +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    plot.title.position = "plot"
  )
}

create_plot <- function(var_string, index, grd = NULL) {
  if (!is.null(grd)) {
    d <- filter(d, grade == grd)
  } 
  counts <- d %>% 
    get_counts(!!sym(var_string))
  
  if (nrow(counts) == 0) {
    message(
      "Item ", 
      gsub("\\.", "", nms[index]), 
      ", had zero responses."
    )
    return("")
  } else {
    plot_counts(counts, index, grd)
  } 
}
```

```{r }
vars <- names(d)[grepl("kind", names(d))]
idxs <- seq_along(vars)

walk2(vars, idxs, ~create_plot(.x, .y) %>%  print())
```

```{r output-by-grade}
output_by_grade <- function(data, grade) {
  cat("\n\\newpage\n\n# Grade", grade)
  
  d %>% 
    filter(.data$grade == grade) %>% 
    create_table() %>% 
    knitr::kable(digits = 2) %>% 
    print()
  
  cat("\n")
  
  walk2(vars, idxs, ~create_plot(.x, .y, grd = grade) %>%  print())
}

```

```{r results = "asis"}
walk(sort(unique(d$grade)), ~output_by_grade(d, grade = .x))
```
