---
author: "Choose Kindness Foundation"
date: "`r format(Sys.Date(), '%m-%d-%y')`"
params:
  file: "data/Jupiter-Elementary-Encuesta-sobre-la-bondad.csv"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
---

---
title: "Individual School Report: `r gsub("SAISD-",  "", gsub("\\.csv", "", basename(params$file))) ` (Results of Spanish Survey)"
---

\newpage

```{r include = FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(knitr.kable.NA = '0%')

theme_set(
  theme_minimal(15)
)

d_all_records <- readr::read_csv(params$file)

new_names <- c(
  "adults_model_kindness",
  "kindness_regular_classroom",
  "kindness_regular_school",
  "teacher_kind",
  "encouraged_kind",
  "grade"
)
names(d_all_records)[8:13] <- new_names

```

```{r}
d <- 
  d_all_records %>% 
  mutate(
    timing = if_else(lubridate::year(date_created) == 2022, 'post', 'pre')
  ) %>% 
  filter(timing == 'post') %>% 
  mutate(
    across(
      .cols = c(
        adults_model_kindness,
        kindness_regular_classroom,
        kindness_regular_school,
        teacher_kind,
        encouraged_kind
        ), 
      .fns =
      ~factor(.x,
          levels = 
            c('En desacuerdo mucho',
              'En desacuerdo poco',
              'No estoy de acuerdo o en desacuerdo',
              'De acuerdo un poco',
              'De acuerdo mucho'
            ), 
          labels = 
            c("Disagree a lot",
              "Disagree a little",
              "Don't agree or disagree",
              "Agree a little",
              "Agree a lot"
            )
        )
      )
  ) 
```

# All Grades

```{r results = "asis"}
nms <- c(
  "Response", 
  "1. The adults in my school model kindness.",
  "2. Kindness happens regularly in my classrooms.",
  "3. Kindness happens regularly in my school.",
  "4. My teacher is kind.",
  "5. At my school I am encouraged to be kind."
)
create_percent <- function(x) {
  paste0(format(round(x, 2), nsmall = 2), "%")  
}

create_table <- function(data, grades_of_interest) {
 cross_tabs <- 
   data %>% 
    filter(grade %in% grades_of_interest) %>% 
    select(respondent_id, contains("kind")) %>% 
    pivot_longer(-respondent_id) %>% 
    drop_na() %>% 
    count(name, value) %>% 
    group_by(name) %>% 
    mutate(
      percent = (n / sum(n)) * 100,
      percent = create_percent(percent)
    ) %>% 
    select(-n) %>% 
    pivot_wider(names_from = "name", values_from = "percent") %>% 
    mutate(
      value = factor(
        value, 
        levels = c(
          "Disagree a lot",
          "Disagree a little",
          "Don't agree or disagree",
          "Agree a little",
          "Agree a lot"
        )
      )
    ) %>% 
   arrange(desc(value)) %>% 
   # next step causes issues if not manually specified order
   select(
     value, 
     adults_model_kindness,
     kindness_regular_classroom,
     kindness_regular_school,
     teacher_kind,
     encouraged_kind
   )

 names(cross_tabs) <- nms
 
 cross_tabs
}

available_grades <- 
  d %>% 
  count(grade) %>% 
  arrange(grade) %>% 
  pull(grade)

create_table(d, grades_of_interest = available_grades) %>% 
  knitr::kable(digits = 2)

available_grades_less_than5 <- 
  d %>% 
  count(grade) %>% 
  arrange(grade) %>% 
  filter(n < 5) %>% 
  pull(grade)

```

```{r eval=FALSE, include=FALSE, results = "asis"}
likely_miscoded <- 
  d %>% 
  filter(grade %in% available_grades_less_than5) %>% 
  select(
    `Respondent ID` = respondent_id, 
    `Survey ID` = survey_id, 
    `Listed Grade` = grade
    ) 

if (available_grades_less_than5 > 0){
  knitr::kable(
    likely_miscoded, 
    digits = 2
    )
}

```

```{r }
get_counts <- function(data, variable) {
  data %>% 
    select({{variable}}) %>% 
    drop_na() %>% 
    count({{variable}}) %>% 
    mutate(
      prop = n / sum(n),
      labels = create_percent(prop * 100),
      nudge_amount = ifelse(prop > 0.1, -0.09, 0.01),
      label_color = ifelse(prop > 0.1, "white", "black"),
      {{variable}} := factor(
        {{variable}},
        levels = c(
          "Disagree a lot",
          "Disagree a little",
          "Don't agree or disagree",
          "Agree a little",
          "Agree a lot"
        )
      )
    )
}


plot_counts <- function(counts_df, item_name, grade) {
  nm <- names(counts_df)[1]
  grade_label <- ifelse(
    is.null(grade), 
    "All Grades", 
    paste0("Grade ", grade)
  )
  
  ggplot(counts_df, aes(prop, !!sym(nm))) +
  geom_col(fill = "cornflowerblue", 
           color = colorspace::darken("cornflowerblue", .3),
           alpha = 0.9) +
  scale_x_continuous(
    "Percentage", 
    limits = 0:110,
    labels = scales::percent,
    expand = c(0, 0) 
  ) +
  scale_y_discrete(drop = FALSE) +
  geom_text(
    aes(label = labels, color = label_color), 
    nudge_x = counts_df$nudge_amount,
    hjust = 0
  ) +
  labs(
    title = item_name,
    y = "",
    caption = paste0(grade_label, "; n = ", sum(counts_df$n))
  ) +
  scale_color_identity() +
  guides(color = "none") +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    plot.title.position = "plot"
  )
}

create_plot <- function(var_string, item_name, grd = NULL) {
  if (!is.null(grd)) {
    d <- filter(d, grade == grd)
  } 
  counts <- d %>% 
    get_counts(!!sym(var_string))
  
  if (nrow(counts) == 0) {
    message(
      "Item ", 
      gsub("\\.", "", nms[item_name]), 
      ", had zero responses."
    )
    return("")
  } else {
    plot_counts(counts, item_name, grd)
  } 
}
```

```{r }
vars <- names(d)[grepl("kind", names(d))]
idxs <- nms[-1]#seq_along(vars)

walk2(vars, idxs, ~create_plot(.x, .y) %>%  print())
```

```{r output-by-grade}
output_by_grade <- function(data, grd) {
  cat("\n\\newpage\n\n# Grade", grd)
  
  d %>% 
    create_table(grades_of_interest = grd) %>% 
    knitr::kable(digits = 2) %>% 
    print()
  
  cat("\n")
  
  walk2(vars, idxs, ~create_plot(.x, .y, grd = grd) %>%  print())
}

```

```{r results = "asis"}
d_only_correctly_coded <- 
  d %>% filter(!grade %in% available_grades_less_than5)

walk(
  sort(
    unique(d_only_correctly_coded$grade)), 
  ~output_by_grade(
    d_only_correctly_coded, 
    grd = .x
    )
  )
```
